name: course_project_spring_2023_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  api_repository:
    path: packages/api_repository

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  formz: ^0.6.0
  date_field: ^3.0.5
  intl: ^0.18.0
  timelines: ^0.1.0
  dcdg: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/courses/
  uses-material-design: true

