name: user_repository
description: Package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.7
  api_repository:
    path: ../api_repository
dev_dependencies:
  very_good_analysis: ^3.1.0