name: api_repository
description: Package which manages the api domain.
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  very_good_analysis: ^3.1.0
dependencies:
  dio: ^5.1.1
